### ISSUE TITLE
removing same settlement twice

### ISSUE THREAD

**Issue by samwarnick** [samwarnick/catan#15]
You know what the problem

**Comment by samwarnick** [comment]
check roads, cities, settlements for duplicate add and remove

**Comment by samwarnick** [comment]
check bounds of victory points?

**Comment by Matt0911** [comment]
the problem might be that a certain vertex can be represented by three different VertexLocations. While implementing BoardFacade I added methods into VertexLocation and EdgeLocation to return lists of the other representations of the same location
