### ISSUE TITLE
Map does not appear for the last player joining

### ISSUE THREAD

**Issue by samwarnick** [samwarnick/catan#47]
I created a new game, added 4 players, and the map showed up for the first 3 players, but not the fourth.

**Comment by Matt0911** [comment]
I havent been able to reduplicate this.... But the map did fail to show up for me once when I logged in using a newly registered user.

**Comment by Matt0911** [comment]
I'm getting a null pointer exception that originates from the joinGameController when I join a game with a newly registered player. This makes it crash before the map loads

**Comment by ihartung** [comment]
ill take a look at that

**Comment by ihartung** [comment]
if (clientPlayer == null){
            clientPlayer = GameModelFacade.getInstance().getGameModel().getPlayer(playerName);
        }
        else {
            clientPlayer = GameModelFacade.getInstance().getGameModel().getPlayer(playerName);
        }

this is the getClientPlayer function in the model controller, I imagine its not supposed to do the same thing in both instances.

**Comment by ihartung** [comment]
i believe this issue is fixed
