### ISSUE TITLE
Robber view doesn't come up in the right order

### ISSUE THREAD

**Issue by gkrieg** [samwarnick/catan#52]
The who you want to rob comes up before you get to place the robber.  Also you need to check if the window is already modal before you make it modal otherwise it will come up every 5 seconds when the poller does its thing

**Comment by samwarnick** [comment]
I can't quite figure this one out

**Comment by Matt0911** [comment]
I'm working on it, I'm close. Unfortunately i realized im in the master branch. Hopefully no merge problems later

**Comment by Matt0911** [comment]
This part of the robber problem is done
