### ISSUE TITLE
Resources aren't updated after the second settlement is built...

### ISSUE THREAD

**Issue by gkrieg** [samwarnick/catan#53]

**Comment by Matt0911** [comment]
I feel like that should be taken care of by the server, its just not being pulled from the model or not being displayed right. Resources also dont get updated after a roll.

**Comment by samwarnick** [comment]
I'll look into it. I know for sure that the server updates resources on rolls, so it makes sense that it would do it after setup too.

**Comment by samwarnick** [comment]
clientPlayer was not being set beyond initialization in ModelController
