### ISSUE TITLE
Can't get port owners for Maritime trade ratios

### ISSUE THREAD

**Issue by gkrieg** [samwarnick/catan#60]
Does anyone know how to get a list of ports that the player currently owns?

**Comment by Matt0911** [comment]
It'll take a lot of iterating and comparing. I'll add a function that will
do it or try to find a way to update the trade ratios for the player when
they build a settlement.

**Comment by gkrieg** [comment]
That will only work until the poller is called.  If you just make a function that updates trade ratios based on the ports owned by the player that would be better.  Or a function that returns a TradeRatios object that I can then use

**Comment by Matt0911** [comment]
Ok, I'll make a function in board facade that return a tradeRatios object

**Comment by gkrieg** [comment]
thanks!
